### ISSUE TITLE
Leerstelle vor Text 

### ISSUE THREAD

**Issue by ipod86** [jack-blackson/ioBroker.countdown#109]
Hallo,

ich habe bei 2 Geburtstagen (mehr habe ich nicht im Adapter) vor ".inWordsLong" eine Leerstelle wenn ich die verbleibende Zeit bis zum Geburtstag berechne.
Wenn ich das Alter berechne, habe ich diese Leerstelle nicht.
Unter den Objekten sieht man die Leerstelle nicht, wenn man den DP aber öffnet sieht man es. 

Andere DPs habe ich nicht überprüft, ist mir gtade in meiner Visualoaufgefallen. 

Adapterversion 2.1.0

**Comment by jack-blackson** [comment]
Servus!

Danke für den Hinweis. Ich hab den Fehler gefunden, und ihn in Version 2.2.0 behoben, welcher seit einigen Minuten im Latest verfügbar ist. Würde mich über ein kurzes Feedback freuen, ob es für dich nun so passt.

**Comment by ipod86** [comment]
Ja, die Leerstelle ist jetzt weg, vielen Dank. 

Die neue Config zum bearbeiten der einzelnen Countdowns ist klasse 👍
