### ISSUE TITLE
JSON-Werte falsch

### ISSUE THREAD

**Issue by ghost** [jack-blackson/ioBroker.countdown#115]
Hey, danke für deinen tollen Adapter! Ich lasse die Countdowns über ein Blockly-Script nach Rest-Tagen sortieren, indem ich die JSON-Werte nach dem JSONata-Ausdruck "$^(Tage )" formatiere. Das hat bis zur aktuellen Version wunderbar funktioniert. Nun ist aber bei "Tage" (und auch bei "Datum" ein Leerzeichen dazugekommen, weshalb ich nicht mehr sortieren kann. Könntest du das Leerzeichen bei der nächsten Version wieder entfernen oder gerne eine Möglichkeit hinzufügen, den Countdown nach verschiedenen Einstellungen sortieren zu lassen?

Aktuell: "Tage " -> Besser: "Tage".

Grüße
Max

**Comment by jack-blackson** [comment]
Hallo! Das schaue ich mir gerne an.

**Comment by jack-blackson** [comment]
Hallo!

Ich habe das geprüft und konnte leider kein Leerzeichen finden. Da dein User inzwischen geblockt ist, bitte ein neues Issue aufmachen, mit Screenshots aus dem ioBroker, bzw. einem klaren Hinweis, welches Objekt du meinst.
