### ISSUE TITLE
Please adapt engines clause and test-and-release Workflow

### ISSUE THREAD

**Issue by mcm1957** [jack-blackson/ioBroker.countdown#135]
test-and-release workflow tests for node.js 20.x and 22.x.
enginse clause at package.json requires node 18 minimum

Either engines clause must require node 20 OR test-and-release workflow must include node 18 tests.

PR to update stable is on hold currently until tests are adapted. No new release is required.

**Comment by jack-blackson** [comment]
@mcm1957  I adjusted it, that also 18 is included. I was removing it because the action threw warnings but will keep it in. Is there anywhere an overview where I always can see which version should be checked by the adapter?

**Comment by mcm1957** [comment]
The adapter should check all node versions ioBroker supports AND are allowed by the adapter (specified by engines clause). Checks should be performed at all platforms (linux, windows, mac) unless technical reasons prohibit this (i.e. RasperryPi GPIOs will noct be useable at a mac :-) )

Currently ioBroker recommends node 20. So this is a must. Node 22 is available and should be testes too. Node 24 is not yet available. Node 18 is still supported by ioBroker. So ist up to you if you test with node 18 or not depending on engines clause. Changes to the recommendes node version are published at forum (forum.iobroker.net)

THANKs for the adaptions and for spending your time.

**Comment by mcm1957** [comment]
OK, test for node 18 have been aded - so we could close here.
