### ISSUE TITLE
no sendto in Blockly

### ISSUE THREAD

**Issue by Leprechaun91** [jack-blackson/ioBroker.countdown#22]
hey, 

there is no sendto available in blockly`

**Comment by jack-blackson** [comment]
Do you have more details? Is this still an open issue? 
<img width="279" alt="grafik" src="https://user-images.githubusercontent.com/13975634/75362789-87dfb300-58b9-11ea-96c8-e1b0a5135172.png">

**Comment by jack-blackson** [comment]
closed as probably not any more relevant - if still, please reopen an issue with some more details.
