### ISSUE TITLE
Update stable version in repo to 1.0.5

### ISSUE THREAD

**Issue by GermanBluefox** [jack-blackson/ioBroker.countdown#27]
# Think about update stable version to 1.0.5
**Version**: stable=**1.0.4** (192 days old) => latest=**1.0.5** (27 days old)
**Installs**: stable=**284** (66.82%), latest=**137** (32.24%), total=**425**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L140)

**Comment by jack-blackson** [comment]
created pull requet to add 1.0.5 to stable
