### ISSUE TITLE
Update stable version in repo to 1.0.5

### ISSUE THREAD

**Issue by GermanBluefox** [jack-blackson/ioBroker.countdown#28]
# Think about update stable version to 1.0.5
**Version**: stable=**1.0.4** (194 days old) => latest=**1.0.5** (30 days old)
**Installs**: stable=**279** (65.8%), latest=**141** (33.25%), total=**424**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L140)

**Comment by jack-blackson** [comment]
Moved to stable
