### ISSUE TITLE
Objekte werden erst nach 1 Minute aktualisiert

### ISSUE THREAD

**Issue by gsicilia82** [jack-blackson/ioBroker.countdown#35]
Hi,

wenn ein neuer Countdown mit "SendTo" erstellt wird, werden die zugehörigen Objekte erst nach einer Minute erstellt und nach einer weiteren Minute mit Inhalt befüllt.
Falls der Countdown bereits vorhanden war und nur neu gestartet wird, dann dauert es dennoch eine Minute bis zur Aktualisierung der States.

Da die States in der Vis genutzt werden, wäre es klasse, wenn sofort nach Start des Timers, die Inhalte der States gesetzt werden. Wäre das möglich?

Danke

**Comment by jack-blackson** [comment]
Hey!

Ich werd mal schauen, was hier machbar ist - verstehe das Problem!

**Comment by jack-blackson** [comment]
Wurde mit 1.2.0 behoben
