### ISSUE TITLE
Ablauf des Timers

### ISSUE THREAD

**Issue by jegow** [jack-blackson/ioBroker.countdown#39]
Wenn ein Einmal-Timer erstellt wurde, dann wird der reached-Zustand beim erreichen auf true gesetzt. Wenn allerdings eine weitere Minute vergangen ist, dann geschieht das gleiche nochmal, alle Events die diesen Zustand aboniert haben, werden erneut ausgelöst. Lässt sich das umgehen?

**Comment by jack-blackson** [comment]
Hallo @jegow ! Arbeitest du mit Blocky? Gehst du auf "geändert" oder "aktualisiert"? Könntest du mir event. dein Blocky zeigen, damit ich sehe, was hier passiert, damit ich es nachvollziehen kann?

**Comment by jegow** [comment]
Ich benutzte Javascript direkt:
`
sendTo("countdown.0", "send", {
    "name": "XXX",
    "addminutes": 2
});
on({id:'countdown.0.countdowns.XXX.reached',val:true},(obj)=>{
    log("XXX ausgelöst");
});
`
Nach der eingestellten Zeit von 2 Minuten erscheint dann die Meldung, aber danach jede weitere Minute. 
`
09:19:09.045 | info | javascript.0 (1381) script.js.TEST.test2: Test
09:20:09.033 | info | javascript.0 (1381) script.js.TEST.test2: Test
09:21:09.067 | info | javascript.0 (1381) script.js.TEST.test2: Test
`
Das kann ich zwar beheben mit `change:'ne'` aber meines erachtens sollte das End-Event nicht erneut ausgelöst werden.

**Comment by jack-blackson** [comment]
Es ist zwar sehr lange her aber ich hoffe endlich eine Lösung für dein Problem in der v 2.0 gefunden zu haben. Vielleicht hast du Lust es nochmal kurz anzusehen und mir Bescheid zu geben.
