### ISSUE TITLE
Abbrechen/Löschen eines Countdowns nicht mehr möglich

### ISSUE THREAD

**Issue by mango1402** [jack-blackson/ioBroker.countdown#56]
Ich möchte einen bestehenden Countdown vor dessen Ablauf Abbrechen bzw. Löschen.
Dies hat mit der vorherigen Version (ich glaub es war V1.2.0) auch bestens funktioniert, so wie in der Doku beschrieben:

> How to delete countdowns
> You can delete a countdown with the sendto. Therefore, send just the name with sendto to the adapter, and the countdown will be deleted automatically.
> 
also dann so:
![image](https://user-images.githubusercontent.com/84717453/121800548-e063cc80-cc32-11eb-95cc-99d6a0c54cb4.png)

Seit V1.2.3 funktioniert dies nicht mehr!
Kommando kommt an, es tut sich aber nichts:

countdown.0 | 2021-06-13 10:20:55.876 | silly | (6950) States system redis pmessage io.messagebox.system.adapter.countdown.0/io.messagebox.system.adapter.countdown.0:{"command":"send","message":{"name":"TV-Sleeptimer"},"from":"system.adapter.javascript.0","_id":50785502}
-- | -- | -- | --

auch ein Setzen der Zeit auf '0' durch 'addminutes' bringt nicht das gewünschte Ergebnis:

countdown.0 | 2021-06-13 10:28:19.897 | error | (6950) TV-Sleeptimer: Adding 0 is invalid
-- | -- | -- | --

Oder gibt es eine andere Möglichkeit, einen Countdown abzubrechen?

**Comment by jack-blackson** [comment]
Hallo!

Nein, da hab ich nichts (absichtlich) geändert - aber wie sich herausstellt hat sich hier eine falsche Spitzklammer in ein IF geschummelt, und schon ging das nicht mehr - danke für den Hinweis! Ich hab es behoben, wenn du die Github-Version über den Link installierst, sollte es wieder gehen. Würde mich über ein kurzes Feedback freuen. Link: https://github.com/jack-blackson/ioBroker.countdown/tarball/v1.2.5

**Comment by mango1402** [comment]
Hallo,

Danke für's rasche fixen!

Ja, klappt wieder einwandfrei:

countdown.0 | 2021-06-14 09:37:08.837 | info | (14482) Delete channel countdown.0.countdowns.TV-Sleeptimer
-- | -- | -- | --
countdown.0 | 2021-06-14 09:37:08.829 | info | (14482) Delete countdown: TV-Sleeptimer
countdown.0 | 2021-06-14 09:37:08.828 | debug | (14482) received send command!
countdown.0 | 2021-06-14 09:37:08.826 | silly | (14482) States system redis pmessage io.messagebox.system.adapter.countdown.0/io.messagebox.system.adapter.countdown.0:{"command":"send","message":{"name":"TV-Sleeptimer"},"from":"system.adapter.javas


lg Manfred

**Comment by mango1402** [comment]
Noch ein kleiner 'Schönheitsfehler':

"en": "Bugfix to delete adapter with sendto",

Man löscht nicht den Adapter, sondern nur einen Countdown.

**Comment by jack-blackson** [comment]
Guter Punkt - hab ich angepasst, danke fürs genaue checken :) Schau mir heute noch dein anderes Issue an.

**Comment by mango1402** [comment]
fixed mit 1.2.5

Danke!
