### ISSUE TITLE
Löschen / Ändern von Countdowns über Adapter Settings

### ISSUE THREAD

**Issue by Lueghi** [jack-blackson/ioBroker.countdown#68]
Man kann ja inzwischen auch Countdowns über die Adapter Settings anlegen. Ich würde mir wünschen, dass man auch eine Übersichtsliste der aktuellen Countdowns hat, in der man sich die Countdowns ansehen / löschen und ggf. ändern kann. Dann muss man nicht umständlich mit Scripten arbeiten ...

**Comment by jack-blackson** [comment]
Hallo! Das ist inzwischen in der Latest/Beta Version verfügbar, der 2.2.0 - schau es dir gerne an, und meld dich falls dir was auffällt.

**Comment by Lueghi** [comment]
Kommt gut! So hatte ich mir das vorgestellt 😎. Danke für Deinen Einsatz.
