### ISSUE TITLE
Counter output two hours to late

### ISSUE THREAD

**Issue by EHRENBEAR** [jack-blackson/ioBroker.countdown#81]
The output of the counter is two hours to late.
As example:

Object ID:
Name "Test"
Date "17.08.2022 17:00"

Actually date & time at me:
16.08.2022 16:29

The ouput of "countdown.0.countdowns.Test.inWordsLong" =  1 Day 2 Hours 30 Minutes

![Bild_2022-08-16_162934792](https://user-images.githubusercontent.com/111368284/184905350-814ed278-eb1b-4ea2-9106-6fe1d90dabbc.png)

**Comment by jack-blackson** [comment]
Hello!

It took some time but I just published version 2.0 to the latest branch, that hopefully should fix that problem. Please check and let me know.

**Comment by jack-blackson** [comment]
This should have been fixed. If it still exists in version 2.0, please create a new issue
