### ISSUE TITLE
incorrect calculation

### ISSUE THREAD

**Issue by Lueghi** [jack-blackson/ioBroker.countdown#91]
There is a fault in the calculation:

countdown date: _01.05.2025_
actual date: _26.04.2023_
Is shows a time of: 2y **1**m **4**d.

In my calculation it should be: 2y 0m 5d.

**Comment by jack-blackson** [comment]
Hey! i found the bug in the calculation. The bugfix is available in this version - do you want to give it a try, and install it via github? https://github.com/jack-blackson/ioBroker.countdown/tarball/v1.3.1

**Comment by Lueghi** [comment]
Can you tell me where I find some information how to install the updated adapter from file? Until now I only used the the update function from iobroker itself ...🤔

**Comment by jack-blackson** [comment]
But please wait, I am working on some more improvements at the moment, I will let you know when all is done and the adapter runs stable again.

**Comment by jack-blackson** [comment]
Now the adapter is ready, in version 2.0. You can find it in the latest/beta channel - so you don't need this link any more. Please let me know if it works.

**Comment by jack-blackson** [comment]
This should have been fixed. If it still exists in version 2.0, please create a new issue
