### ISSUE TITLE
[DOCU] Adapt revision header size to satisfy adapter checker

### ISSUE THREAD

**Issue by mcm1957** [jack-blackson/ioBroker.countdown#95]
Please correct revision history entries at README:md to avoid errors reported by adapter checker.

Revision headers should (must) be heder level 3 sized (###). So please replace

```## Changelog

## 2.0.1 (2023-05-24) 
* (jack-blackson) Added objects for total number of months and years
```
by

```## Changelog

### 2.0.1 (2023-05-24) 
* (jack-blackson) Added objects for total number of months and years
```
in futuere.

Thanks for your cooperation
McM1957

**Comment by jack-blackson** [comment]
Done
