### ISSUE TITLE
Stunden unlogisch 

### ISSUE THREAD

**Issue by ipod86** [jack-blackson/ioBroker.countdown#96]
Hallo,

ich habe bei meinen countdowns für Geburtstage gemerkt, dass bei einem Geburtstag die Stunden unlogisch sind.
Alle Geburtstage liegen auf 00:00 Uhr.

Anbei ein Screenshot.
Alle Countdowns haben 14h, nur einer 15h.

Die Termine im Setup:
02.11.2023 00:00:00+1Y
19.09.2023 00:00:00+1Y
06.08.2023 00:00:00+1Y

![Screenshot_20230617_093121_Chrome](https://github.com/jack-blackson/ioBroker.countdown/assets/66136363/f2de9d3c-0a2b-43cc-8cf2-fffbc98d506d)

**Comment by jack-blackson** [comment]
Meine erste Vermutung wäre jetzt die Winterzeitumstellung - ich schau es mir aber gerne an.

**Comment by ipod86** [comment]
Danke.
Hab es mir grad nochmal angeschaut.
Jetzt haben beide sie selben Stunden.

Komisch.....

**Comment by jack-blackson** [comment]
Ich schließe das mal, wenn es wieder auftaucht bitte nochmal melden, oder das Issue wieder öffnen.
