### ISSUE TITLE
Babyalter

### ISSUE THREAD

**Issue by Mephisto090** [jack-blackson/ioBroker.countdown#97]
Hallo,

eine kleine Idee für dich. Für Eltern, wie mich, ist es manchmal wichtig zu wissen wie Alt das Baby ist. Kannst du ggf. eine Funktion einbauen wo es kein Countdown ist sondern ein "wie lange ist es her"? Sprich ich gebe das Geburtstag des Kindes ein und er sagt mir es ist 6 Monate und 5 Tage alt oder es ist 1 Jahr, 6 Monate und 7 Tage alt?

Beispiel: https://www.hallo-eltern.de/wochenrechner/

![image](https://github.com/jack-blackson/ioBroker.countdown/assets/85995176/38394fda-eb93-4ecd-b931-51094a87222f)
![image](https://github.com/jack-blackson/ioBroker.countdown/assets/85995176/da7e3241-ba54-48b6-9a1c-98b70edfcb9e)

VG
Florian

**Comment by jack-blackson** [comment]
Finde ich eine gute Idee - wurde auch bereits einmal als Feature gewünscht. Ich muss mir nur überlegen, wie ich das am besten regle - wie ich weiß, ob jemand einen Countdown oder einen "Count Up" will. Darüber muss ich noch etwas nachdenken.

**Comment by Mephisto090** [comment]
Ah cool, freue mich auf das neue Feature :D 

Weißt du schon, wann du Zeit findest es umzusetzen?

**Comment by jack-blackson** [comment]
Ich bin gerade dran, ist schon fast fertig, hoffe es die nächsten Tage bereitstellen zu können - möchte es noch gründlich testen.

**Comment by jack-blackson** [comment]
Nun ist das neue Feature bereit zum testen. Du findest es in der Version 2.1.0 (sollte in 1-2 Stunden verfügbar sein) im Latest/Beta Channel. Hab auch das ReadMe angepasst - unter dem Stichwort "CountUp" zu finden. Würde mich über Feedback freuen.
