### ISSUE TITLE
Ändern eines bereits laufenden Timers 

### ISSUE THREAD

**Issue by olli-70** [jack-blackson/ioBroker.countdown#99]
Die Möglichkeit, einen laufenden Timer zu ändern ohne ihn vorher löschen zu müssen wäre klasse.

**Comment by jack-blackson** [comment]
Hallo!

Wie erstellst du die Timer? Ansich kann man, wenn man sie z.B. über Script oder SendTo erstellt, einfach "überschreiben" - hier einfach den selben Namen verwenden, und der Adapter wird aktualisiert.

**Comment by olli-70** [comment]
oh, sorry hatte vergessen das "als gelöst" zu melden ;)
